name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nelsonjchen/gh-pages-pelican-action@0.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#    - name: Upload ftp
#      uses: genietim/ftp-action@releases/v4
#      with:
#        host: ${{ secrets.FTP_SERVER }}
#        user: ${{ secrets.FTP_USERNAME }}
#        password: ${{ secrets.FTP_PASSWORD }}
#        localDir: "dist"
#        remoteDir: "www"
